- hosts: observatory
  remote_user: root
  gather_facts: false
  vars:
    - log_file: "/opt/observatory.log"
    - server_dir: "/opt/Observatory3/"
  tasks:
    - command: /usr/local/bin/forever stopall

    - fail: msg="Missing Observatory version. Pass with --extra-vars release=v0.0.1"
      when: release is undefined

    - git: 
        repo='https://github.com/rcos/Observatory3.git'
        version="{{ release }}"
        dest="{{ server_dir }}"

    - command: /usr/local/bin/npm install
      args:
        chdir: "{{ server_dir }}"

    - command: /usr/local/bin/grunt --force
      args:
        chdir: "{{ server_dir }}"

    - shell: "NODE_ENV=production PORT=80 forever -a -l {{ log_file }} start {{ server_dir }}dist/server/app.js"
